#!/bin/sh

regex=".*\.c$\|.*\.cc$\|.*\.c\+\+$\|.*\.cc$\|.*\.cpp$\|.*\.cxx$\|.*\.m$\|.*\.M$\|.*\.mm$\|.*\.h$\|.*\.hh$\|.*\.h\+\+$\|.*\.hm$\|.*\.hpp$\|.*\.hxx$\|.*\.txx$"
regex_clean=".*\.c\~$\|.*\.cc\~$\|.*\.c\+\+\~$\|.*\.cc\~$\|.*\.cpp\~$\|.*\.cxx\~$\|.*\.m\~$\|.*\.M\~$\|.*\.mm\~$\|.*\.h\~$\|.*\.hh\~$\|.*\.h\+\+\~$\|.*\.hm\~$\|.*\.hpp\~$\|.*\.hxx\~$\|.*\.txx\~$"

find . -iregex $regex -exec indent '{}' \;
find . -iregex $regex_clean -exec rm '{}' \;
find . -iregex $regex | xargs perl -pi -e 's/\t/    /g'
