#!/bin/sh

find . -name "*.[h,c]" -exec indent '{}' \; -o -name "*.cpp" -exec indent '{}' \;
find . -name "*.h~" -exec rm '{}' \; -o -name "*.c~" -exec rm '{}' \; -o -name "*.cpp~" -exec rm '{}' \;
find -name "*.[hc]" | xargs perl -pi -e 's/\t/    /g'
find -name "*.cpp" | xargs perl -pi -e 's/\t/    /g'
